<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Monday 17th of March 2014 12:10:40 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://www.klipsam.com/birdy/helpers/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "871528867130.apps.googleusercontent.com", "secret" => "pZd5C-MfjCVIGLvD3K0h8Jg4" ),
				"scope"   => "email https://www.googleapis.com/auth/plus.login"
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "708342695852571", "secret" => "bd94c8e354b3a2db7a5fbac357782041" ),
				"display" => "popup" // optional
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "S8iQJTtq6zJpDZltUFEkg", "secret" => "dQfHIU528A9E5lM9IPEWmSdlWDZCgwwhhsKBM0mBs" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
